apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nlnrgtbg9-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nlnrgtbg9-nodejs 
  name: nlnrgtbg9-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nlnrgtbg9-nodejs 
